### ISSUE TITLE
Only apply transform if image is above certain width

### ISSUE THREAD

**Issue by katrinkerber** [mmikkel/RetconHTML-Craft#11]
I'd like to only apply transforms to images that exceed a certain width.

For 'normal' image transforms, I use this transform code to achieve this:

`{{ image.getUrl({ width: min(846, image.width) }) }}`

Is there something similar I can do with this plugin?

**Comment by mark-chief** [comment]
+1 
Did you find a solution? Appreciate it was some time ago!
:)

**Comment by mmikkel** [comment]
Hi @mark-chief – FYI this is the repo for the Craft 2 version of Retcon; I've just neglected to archive it, but I'm just about to do that :)

The Craft 3 and 4 version can be found here: https://github.com/mmikkel/Retcon-Craft

Concerning this particular issue – it's not something I think should be fixed/done in Retcon; the plugin transforms images either using the core Craft transforms (in which case the [`upscaleImages`](https://craftcms.com/docs/4.x/config/general.html#upscaleimages) setting would apply) or the Imager plugin if it's installed (in which case its [`allowUpscale`](https://imager-x.spacecat.ninja/configuration.html#general-configuration) setting will apply.
