### ISSUE TITLE
Manipulate HTML based on entry details

### ISSUE THREAD

**Issue by bravokiloecho** [mmikkel/RetconHTML-Craft#7]
I've just stumbled across this plugin after searching for methods of manipulating the content of Rich Text fields, and I'm super impressed and pleased by everything that it can do. It will definitely become a staple of my Craft builds.

However, what I was hoping to do in particular was manipulate HTML based on queries relating to dynamic content. For example, if a client creates a link to an entry in a rich text field, this gets stored in the database using a [reference tag](https://craftcms.com/docs/reference-tags) to that entry that looks like this:

```
<p><a href="{entry:10:url}">Link to page</a></p>
```

What I was then hoping to do is something along the lines of

```
if (entry.type == 'news' ) {
    // add class "news-link" to the '<a>' tag
}
```

Is this the kind of thing your plugin can already do? And if not, can you think of any way this might be possible? I can imagine this would be quite a useful feature to have for many sites...

Thanks again for all your work on the plugin so far!

**Comment by mmikkel** [comment]
Hello @bravokiloecho – thanks for contributing!

Nope, what you want unfortunately isn't possible with Retcon. I _have_ been thinking of adding some kind of conditional logic to the plugin (i.e. "add attribute A where attribute `href` starts with http" or "add attribute B for `p` tags containing `h2` tags). No idea if I'll ever get it done, I very rarely need something like that myself.

It's very unlikely that I'll ever cover your specific use case though (drilling down and actually pulling entries etc. based on href tags would be... convoluted), so I'm going to close this as a wontfix, sorry.

Adding a classname (or any other attribute) to `<a>` tags based on the entry type of their linked entries is certainly _doable_, though – I just offered some code for a similar problem on Stack Exchange – you may or not be that question's author! – see http://craftcms.stackexchange.com/questions/12937/treat-links-in-redactor-rich-text-field-differently-depending-on-entry-type. I just think you'll be better off writing a custom plugin for something like that.

Again, thanks for contributing and the nice words!

**Comment by bravokiloecho** [comment]
Hi @mmikkel.

Thanks for your response and I totally understand your reasoning for the wontfix. Your plugin remains super helpful nonetheless. So thanks again for its creation.

ps
It was me who authored the stack exchange question! So you have actually helped enormously. I will reply there properly now.
