### ISSUE TITLE
Add 'retina option' for transform

### ISSUE THREAD

**Issue by m9dfukc** [mmikkel/RetconHTML-Craft#8]
Please add the option for automatically transform the image to retina and nonretina resolutions and output the image tag with srcset the attribute.

**Comment by mmikkel** [comment]
Hi @m9dfukc, thanks for contributing. I plan to make some big changes to the `retconTransform` filter as soon as I have the time. Adding support for responsive images (srcset and/or picture) is definitely in the cards. Can't give you an ETA, but watch this spot :)

**Comment by mmikkel** [comment]
See the new [`srcset`](https://github.com/mmikkel/RetconHTML-Craft/wiki/srcset) filter in [Retcon 1.3](https://github.com/mmikkel/RetconHTML-Craft/releases/tag/1.3.0).

**Comment by m9dfukc** [comment]
A little late but just coming back to this ... thank you very much, that helps a lot I my current project!!!

**Comment by mmikkel** [comment]
That's awesome @m9dfukc – very happy to be able to help out.
